import Head from 'next/head'
import styles from '../styles/Home.module.css'
import State from './state'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <State />
      </main>

      <footer className={styles.footer}>
        The main tool to stay focused is to plan the task and motivate its development.
      </footer>
    </div>
  )
}
